name: CI/CD Simple Web Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  # GIAI ĐOẠN 1: CI (Chạy trên máy ảo đám mây của GitHub để test)
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Kéo code về test
        uses: actions/checkout@v4

      - name: Chạy script kiểm thử
        run: |
          chmod +x test.sh
          ./test.sh

  # GIAI ĐOẠN 2: CD (Chạy trực tiếp trên máy ảo VMware của bạn)
  continuous-deployment:
    needs: continuous-integration
    runs-on: self-hosted
    steps:
      - name: Kéo code mới nhất về VMware
        uses: actions/checkout@v4

      - name: Copy file vào thư mục web Nginx
        run: |
          cp index.html /var/www/html/